rg2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  
  gripper_joint_position:
    type: effort_controllers/JointPositionController
    joint: gripper_joint
    pid: {p: 5, i: 0.0, d: 0.0}
  # l_finger_2_joint_position:
  #   type: effort_controllers/JointPositionController
  #   joint: l_finger_2_joint
  #   pid: {p: 5, i: 0.0, d: 0.0}
  # l_finger_passive_joint_position:
  #   type: effort_controllers/JointPositionController
  #   joint: l_finger_passive_joint
  #   pid: {p: 5, i: 0.0, d: 0.0}
  # r_finger_1_joint_position:
  #   type: effort_controllers/JointPositionController
  #   joint: r_finger_1_joint
  #   pid: {p: 5, i: 0.0, d: 0.0}
  # r_finger_2_joint_position:
  #   type: effort_controllers/JointPositionController
  #   joint: r_finger_2_joint
  #   pid: {p: 5, i: 0.0, d: 0.0}
  # r_finger_passive_joint_position:
  #   type: effort_controllers/JointPositionController
  #   joint: r_finger_passive_joint
  #   pid: {p: 5, i: 0.0, d: 0.0}